# Generated by Django 6.0.5 on 2026-05-11 13:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern'), ('warning', 'Warning'), ('suggestion', 'Suggestion')], db_index=True, max_length=20)),
                ('was_useful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_patterns', models.JSONField(default=dict)),
                ('productivity_peaks', models.JSONField(default=dict)),
                ('avg_session_duration', models.IntegerField(blank=True, null=True)),
                ('project_completion_rate', models.FloatField(blank=True, null=True)),
                ('focus_areas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('obstacles_log', models.JSONField(default=dict)),
                ('streak_data', models.JSONField(default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
